apiVersion: v1
kind: Namespace
metadata:
  name: openai
---
apiVersion: v1
kind: Secret
metadata:
  namespace: openai
  name: openai
type: Opaque
data:
  OPENAI_API_KEY: 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
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: openai
  name: openai
  labels:
    app: openai
spec:
  replicas: 1
  selector:
    matchLabels:
      app: openai
  template:
    metadata:
      labels:
        app: openai
    spec:
      containers:
        - name: openai
          image: <docker user>/openai:latest
          resources: {}
          ports:
            - containerPort: 3000
          env:
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: openai
                  key: OPENAI_API_KEY
---
kind: Service
apiVersion: v1
metadata:
  namespace: openai
  name: openai
  labels:
    app: openai
spec:
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3000
  selector:
    app: openai
  type: ClusterIP
